In [21]:
#Numpy 2d arrays
##
import numpy as np
a=[[11,12,13],[21,22,23],[31,32,33]]
A=np.array(a)
print(A)
A.ndim # 2  (0,1,2)
A.shape # returns the tuple (3,3)
A.size # number of elements 3*3 = 9
A[0][1] # row0, col1
A[0] # row0

#Slicing
A[0,0:2] # row0, col0,1
A[0:2,2] # row0,1 ; col2

[[11 12 13]
 [21 22 23]
 [31 32 33]]


array([13, 23])

In [51]:
# Numpy 2d arrays Addition
##
x=np.array([[1,0],[0,1]])
y=np.array([[2,1],[1,2]])
z=x+y
print(z)
w= 2*y
print(w)
t= x*y
print(t)
v= np.dot(x,y)
print(v)

[[3 1]
 [1 3]]
[[4 2]
 [2 4]]
[[2 0]
 [0 2]]
[[2 1]
 [1 2]]


In [37]:
#Matrix multiplication
#matA=2x3 3x2=matB -> matAB= 2x2

A=np.array([[0,1,1],[1,0,1]]) # 2x3
B=np.array([[1,0],[0,1],[-1,1]]) #3x2
C=np.dot(A,B)
print(C)

[[-1  2]
 [ 0  1]]
